export const dinComponentsActions = {
  SET_MENU: 'SET_MENU',
  SHOW_MODAL_ADD_CATEGORY: 'SHOW_MODAL_ADD_CATEGORY',
  SHOW_DETAILS_CATEGORY: 'SHOW_DETAILS_CATEGORY',
  HIDE_MODAL: 'HIDE_MODAL',
};

export const dinComponentsMutations = {
  SET_SUB_MENU: 'SET_SUB_MENU',
  SET_MODAL_COMPONENT: 'SET_MODAL_COMPONENT',
};
